/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalizedChildrensBooksRouteImport } from './routes/personalized-childrens-books'
import { Route as MyPacksRouteImport } from './routes/my-packs'
import { Route as KidsLearningBooksRouteImport } from './routes/kids-learning-books'
import { Route as GiftGuideRouteImport } from './routes/gift-guide'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ThemesSlugRouteImport } from './routes/themes/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizedChildrensBooksRoute =
  PersonalizedChildrensBooksRouteImport.update({
    id: '/personalized-childrens-books',
    path: '/personalized-childrens-books',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyPacksRoute = MyPacksRouteImport.update({
  id: '/my-packs',
  path: '/my-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLearningBooksRoute = KidsLearningBooksRouteImport.update({
  id: '/kids-learning-books',
  path: '/kids-learning-books',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftGuideRoute = GiftGuideRouteImport.update({
  id: '/gift-guide',
  path: '/gift-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/themes': typeof ThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/contact'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/terms'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/themes/$slug'
    | '/blog/'
    | '/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/contact'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/terms'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/themes/$slug'
    | '/blog'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/confirm-email'
    | '/contact'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/terms'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/themes/$slug'
    | '/blog/'
    | '/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ContactRoute: typeof ContactRoute
  GiftGuideRoute: typeof GiftGuideRoute
  KidsLearningBooksRoute: typeof KidsLearningBooksRoute
  MyPacksRoute: typeof MyPacksRoute
  PersonalizedChildrensBooksRoute: typeof PersonalizedChildrensBooksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalized-childrens-books': {
      id: '/personalized-childrens-books'
      path: '/personalized-childrens-books'
      fullPath: '/personalized-childrens-books'
      preLoaderRoute: typeof PersonalizedChildrensBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-packs': {
      id: '/my-packs'
      path: '/my-packs'
      fullPath: '/my-packs'
      preLoaderRoute: typeof MyPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-learning-books': {
      id: '/kids-learning-books'
      path: '/kids-learning-books'
      fullPath: '/kids-learning-books'
      preLoaderRoute: typeof KidsLearningBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-guide': {
      id: '/gift-guide'
      path: '/gift-guide'
      fullPath: '/gift-guide'
      preLoaderRoute: typeof GiftGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ContactRoute: ContactRoute,
  GiftGuideRoute: GiftGuideRoute,
  KidsLearningBooksRoute: KidsLearningBooksRoute,
  MyPacksRoute: MyPacksRoute,
  PersonalizedChildrensBooksRoute: PersonalizedChildrensBooksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BlogSlugRoute: BlogSlugRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
