/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalizedChildrensBooksRouteImport } from './routes/personalized-childrens-books'
import { Route as MyPacksRouteImport } from './routes/my-packs'
import { Route as KidsLearningBooksRouteImport } from './routes/kids-learning-books'
import { Route as GiftGuideRouteImport } from './routes/gift-guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ThemesSlugRouteImport } from './routes/themes/$slug'
import { Route as ReaderBookIdRouteImport } from './routes/reader.$bookId'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'
import { Route as AuthMagicRouteImport } from './routes/auth.magic'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPromoRouteImport } from './routes/admin/promo'
import { Route as AdminPrintRouteImport } from './routes/admin/print'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminAlarmsRouteImport } from './routes/admin/alarms'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as BlogAuthorIdRouteImport } from './routes/blog/author/$id'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizedChildrensBooksRoute =
  PersonalizedChildrensBooksRouteImport.update({
    id: '/personalized-childrens-books',
    path: '/personalized-childrens-books',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyPacksRoute = MyPacksRouteImport.update({
  id: '/my-packs',
  path: '/my-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLearningBooksRoute = KidsLearningBooksRouteImport.update({
  id: '/kids-learning-books',
  path: '/kids-learning-books',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftGuideRoute = GiftGuideRouteImport.update({
  id: '/gift-guide',
  path: '/gift-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/admin/promo',
  path: '/admin/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrintRoute = AdminPrintRouteImport.update({
  id: '/admin/print',
  path: '/admin/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlarmsRoute = AdminAlarmsRouteImport.update({
  id: '/admin/alarms',
  path: '/admin/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuthorIdRoute = BlogAuthorIdRouteImport.update({
  id: '/blog/author/$id',
  path: '/blog/author/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alarms': typeof AdminAlarmsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print': typeof AdminPrintRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alarms': typeof AdminAlarmsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print': typeof AdminPrintRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/gift-guide': typeof GiftGuideRoute
  '/kids-learning-books': typeof KidsLearningBooksRoute
  '/my-packs': typeof MyPacksRoute
  '/personalized-childrens-books': typeof PersonalizedChildrensBooksRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alarms': typeof AdminAlarmsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print': typeof AdminPrintRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/create'
    | '/dashboard'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/world'
    | '/admin/admins'
    | '/admin/alarms'
    | '/admin/orders'
    | '/admin/print'
    | '/admin/promo'
    | '/admin/settings'
    | '/auth/magic'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/reader/$bookId'
    | '/themes/$slug'
    | '/admin/'
    | '/blog/'
    | '/themes/'
    | '/blog/author/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/create'
    | '/dashboard'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/world'
    | '/admin/admins'
    | '/admin/alarms'
    | '/admin/orders'
    | '/admin/print'
    | '/admin/promo'
    | '/admin/settings'
    | '/auth/magic'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/reader/$bookId'
    | '/themes/$slug'
    | '/admin'
    | '/blog'
    | '/themes'
    | '/blog/author/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/create'
    | '/dashboard'
    | '/gift-guide'
    | '/kids-learning-books'
    | '/my-packs'
    | '/personalized-childrens-books'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/world'
    | '/admin/admins'
    | '/admin/alarms'
    | '/admin/orders'
    | '/admin/print'
    | '/admin/promo'
    | '/admin/settings'
    | '/auth/magic'
    | '/billing/cancel'
    | '/billing/success'
    | '/blog/$slug'
    | '/book/$bookId'
    | '/reader/$bookId'
    | '/themes/$slug'
    | '/admin/'
    | '/blog/'
    | '/themes/'
    | '/blog/author/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  GiftGuideRoute: typeof GiftGuideRoute
  KidsLearningBooksRoute: typeof KidsLearningBooksRoute
  MyPacksRoute: typeof MyPacksRoute
  PersonalizedChildrensBooksRoute: typeof PersonalizedChildrensBooksRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  WorldRoute: typeof WorldRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAlarmsRoute: typeof AdminAlarmsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPrintRoute: typeof AdminPrintRoute
  AdminPromoRoute: typeof AdminPromoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AuthMagicRoute: typeof AuthMagicRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
  BlogAuthorIdRoute: typeof BlogAuthorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalized-childrens-books': {
      id: '/personalized-childrens-books'
      path: '/personalized-childrens-books'
      fullPath: '/personalized-childrens-books'
      preLoaderRoute: typeof PersonalizedChildrensBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-packs': {
      id: '/my-packs'
      path: '/my-packs'
      fullPath: '/my-packs'
      preLoaderRoute: typeof MyPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-learning-books': {
      id: '/kids-learning-books'
      path: '/kids-learning-books'
      fullPath: '/kids-learning-books'
      preLoaderRoute: typeof KidsLearningBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-guide': {
      id: '/gift-guide'
      path: '/gift-guide'
      fullPath: '/gift-guide'
      preLoaderRoute: typeof GiftGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/admin/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/print': {
      id: '/admin/print'
      path: '/admin/print'
      fullPath: '/admin/print'
      preLoaderRoute: typeof AdminPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alarms': {
      id: '/admin/alarms'
      path: '/admin/alarms'
      fullPath: '/admin/alarms'
      preLoaderRoute: typeof AdminAlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/author/$id': {
      id: '/blog/author/$id'
      path: '/blog/author/$id'
      fullPath: '/blog/author/$id'
      preLoaderRoute: typeof BlogAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  GiftGuideRoute: GiftGuideRoute,
  KidsLearningBooksRoute: KidsLearningBooksRoute,
  MyPacksRoute: MyPacksRoute,
  PersonalizedChildrensBooksRoute: PersonalizedChildrensBooksRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  WorldRoute: WorldRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAlarmsRoute: AdminAlarmsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPrintRoute: AdminPrintRoute,
  AdminPromoRoute: AdminPromoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AuthMagicRoute: AuthMagicRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
  BlogAuthorIdRoute: BlogAuthorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
