/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPacksRouteImport } from './routes/my-packs'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'

const MyPacksRoute = MyPacksRouteImport.update({
  id: '/my-packs',
  path: '/my-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/my-packs': typeof MyPacksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/my-packs': typeof MyPacksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/my-packs': typeof MyPacksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/my-packs'
    | '/billing/cancel'
    | '/billing/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/my-packs'
    | '/billing/cancel'
    | '/billing/success'
  id:
    | '__root__'
    | '/'
    | '/confirm-email'
    | '/my-packs'
    | '/billing/cancel'
    | '/billing/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  MyPacksRoute: typeof MyPacksRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-packs': {
      id: '/my-packs'
      path: '/my-packs'
      fullPath: '/my-packs'
      preLoaderRoute: typeof MyPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  MyPacksRoute: MyPacksRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
